default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: authentication_app_development

test:
  <<: *default
  database: authentication_app_test

production:
  <<: *default
  database: authentication_app_production
  username: authentication_app
  password: <%= ENV['AUTHENTICATION_APP_DATABASE_PASSWORD'] %>
